name: publish to github pages
on: push

jobs:
  publish:
    name: generate
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm run publish
